### ISSUE TITLE
For newer PHP versions, refactor GetProxyDetails

### ISSUE THREAD

**Issue by atom-box** [ip2location/ip2proxy-matomo#35] opened 2023-03-17 18:49 UTC
When running with Matomo 4.13.3, PHP 8.1 I get this deprecation warning:

_WARNING: /plugins/IP2Proxy/Reports/GetProxyDetails.php(104): Deprecated - Creation of dynamic property Piwik\Plugins\IP2Proxy\Reports\GetProxyDetails::$columns is deprecated - Matomo 4.13.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreAdminHome, Action: home, In CLI mode: false)_

**Comment by ip2location-com** [comment] 2023-03-19 23:43
The issue is fixed in version 0.1.4.

**Closed as completed by ip2location-com** 2023-03-19 23:43 UTC
